
package com.jackie.createapidemo.api.model.enum

enum class OrderStatusView(val value:String){
	PENDING_PAYMENT("PENDING_PAYMENT"),PAID("PAID"),PENDING("PENDING"),IN_TRANSIT("IN_TRANSIT"),IN_COOKING("IN_COOKING"),FOOD_IS_READY("FOOD_IS_READY"),DELIVERED("DELIVERED"),CANCELED("CANCELED"),PAYMENT_FAILED("PAYMENT_FAILED")
}