
package com.jackie.createapidemo.api.model.enum

enum class TipTypeView(val value:String){
	TEN_PERCENT("TEN_PERCENT"),FIFTEEN_PERCENT("FIFTEEN_PERCENT"),TWENTY_PERCENT("TWENTY_PERCENT"),TWENTY_FIVE_PERCENT("TWENTY_FIVE_PERCENT"),CUSTOM("CUSTOM"),DOLLAR_ONE("DOLLAR_ONE"),DOLLAR_TWO("DOLLAR_TWO"),DOLLAR_THREE("DOLLAR_THREE"),DOLLAR_FOUR("DOLLAR_FOUR")
}